const image = (id, w=800) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=${w}&q=82`;
const products = [
 {id:1,name:'Classic Pique T-Shirt',cat:'T-Shirts',price:1490,collection:'RED POLO',colors:['#151615','#edeae2','#9b9a91'],img:image('photo-1521572163474-6864f9cf17ab'),rating:'4.9',reviews:48,tag:'Bestseller',featured:true},
 {id:2,name:'Essential Cotton T-Shirt',cat:'T-Shirts',price:1190,collection:'RED POLO',colors:['#edeae2','#263238','#a32c2a'],img:image('photo-1581655353564-df123a1eb820'),rating:'4.8',reviews:31,tag:'New',featured:true},
 {id:3,name:'Heavyweight Crew T-Shirt',cat:'T-Shirts',price:1690,collection:'UDUOOCI',colors:['#252624','#b9b0a2'],img:image('photo-1503342217505-b0a15ec3261c'),rating:'4.7',reviews:24,featured:true},
 {id:4,name:'Fine Ribbed Polo',cat:'T-Shirts',price:1890,collection:'UDUOOCI',colors:['#1d1e1b','#f0eee9'],img:image('photo-1551488831-00ddcb6c6bd3'),rating:'4.8',reviews:20},
 {id:5,name:'Oxford Classic Shirt',cat:'Shirts',price:2490,collection:'RED POLO',colors:['#f4f2ed','#263744'],img:image('photo-1602810318383-e386cc2a3ccf'),rating:'4.9',reviews:36,tag:'Bestseller',featured:true},
 {id:6,name:'Relaxed Linen Shirt',cat:'Shirts',price:2790,collection:'UDUOOCI',colors:['#d9d1c4','#24302a'],img:image('photo-1596755094514-f87e34085b2c'),rating:'4.7',reviews:18,tag:'New',featured:true},
 {id:7,name:'Premium Casual Shirt',cat:'Shirts',price:2290,collection:'RED POLO',colors:['#242825','#eeeae1'],img:image('photo-1598033129183-c4f50c736f10'),rating:'4.8',reviews:28},
 {id:8,name:'Textured Resort Shirt',cat:'Shirts',price:2990,collection:'UDUOOCI',colors:['#c7b9a2','#303431'],img:image('photo-1620012253295-c15cc3e65df4'),rating:'4.6',reviews:11,tag:'New'},
 {id:9,name:'Signature Leather Belt',cat:'Belts',price:1790,collection:'RED POLO',colors:['#211714','#282725'],img:image('photo-1624222247344-550fb60583dc'),rating:'4.9',reviews:19,tag:'Bestseller',featured:true},
 {id:10,name:'Slim Leather Belt',cat:'Belts',price:1590,collection:'RED POLO',colors:['#3e2419','#141515'],img:image('photo-1553062407-98eeb64c6a62'),rating:'4.7',reviews:12},
 {id:11,name:'Suede Contrast Belt',cat:'Belts',price:1990,collection:'UDUOOCI',colors:['#a68160','#38332d'],img:image('photo-1553483842-cd2d3f0c6e6b'),rating:'4.7',reviews:9},
 {id:12,name:'Everyday Leather Belt',cat:'Belts',price:1490,collection:'RED POLO',colors:['#1d1e1b'],img:image('photo-1516655855035-d5215bcb5604'),rating:'4.6',reviews:8},
 {id:13,name:'Classic Court Sneakers',cat:'Shoes',price:3490,collection:'RED POLO',colors:['#f4f3ed','#1d1e1b'],img:image('photo-1542291026-7eec264c27ff'),rating:'4.8',reviews:43,tag:'Bestseller',featured:true},
 {id:14,name:'Leather Minimal Sneakers',cat:'Shoes',price:4290,collection:'UDUOOCI',colors:['#e8e4da','#272522'],img:image('photo-1491553895911-0055eca6402d'),rating:'4.9',reviews:27,tag:'New'},
 {id:15,name:'Canvas Weekend Shoes',cat:'Shoes',price:2990,collection:'RED POLO',colors:['#beb4a5','#343a38'],img:image('photo-1525966222134-fcfa99b8ae77'),rating:'4.6',reviews:14},
 {id:16,name:'City Derby Shoes',cat:'Shoes',price:4990,collection:'UDUOOCI',colors:['#231b18'],img:image('photo-1614252235316-8c857d38b5f4'),rating:'4.8',reviews:13},
 {id:17,name:'Everyday Cotton Socks',cat:'Socks',price:590,collection:'RED POLO',colors:['#f3f0ea','#151615','#89908c'],img:image('photo-1586350977771-b3b0abd50c82'),rating:'4.8',reviews:39,tag:'Bestseller',featured:true},
 {id:18,name:'Ribbed Ankle Socks',cat:'Socks',price:490,collection:'RED POLO',colors:['#edeae2','#a32c2a'],img:image('photo-1582966772680-860e372bb558'),rating:'4.7',reviews:17},
 {id:19,name:'Merino Blend Socks',cat:'Socks',price:790,collection:'UDUOOCI',colors:['#31332e','#b6aa9b'],img:image('photo-1586350977771-b3b0abd50c82'),rating:'4.9',reviews:10,tag:'New'},
 {id:20,name:'Signature Stripe Socks',cat:'Socks',price:650,collection:'RED POLO',colors:['#1d1e1b','#edeae2'],img:image('photo-1586350977771-b3b0abd50c82'),rating:'4.6',reviews:8},
 {id:21,name:'Pima Cotton Polo',cat:'T-Shirts',price:1990,collection:'UDUOOCI',colors:['#263a33','#e8e0d3'],img:image('photo-1562157873-818bc0726f68'),rating:'4.8',reviews:21,tag:'New'},
 {id:22,name:'Travel Overshirt',cat:'Shirts',price:3290,collection:'UDUOOCI',colors:['#383f3c','#c5b9a4'],img:image('photo-1603252109303-2751441dd157'),rating:'4.7',reviews:12},
 {id:23,name:'Suede Penny Loafers',cat:'Shoes',price:5490,collection:'UDUOOCI',colors:['#654b39'],img:image('photo-1533867617858-e7b97e060509'),rating:'4.9',reviews:16,tag:'New'},
 {id:24,name:'Reversible Dress Belt',cat:'Belts',price:2190,collection:'UDUOOCI',colors:['#151615','#6c4533'],img:image('photo-1624222247344-550fb60583dc'),rating:'4.8',reviews:12},
 {id:25,name:'Lounge Terry Tee',cat:'T-Shirts',price:1590,collection:'UDUOOCI',colors:['#cfc8bc','#353937'],img:image('photo-1576566588028-4147f3842f27'),rating:'4.7',reviews:10},
 {id:26,name:'Brushed Cotton Shirt',cat:'Shirts',price:2890,collection:'RED POLO',colors:['#9ca3a0','#ece9e1'],img:image('photo-1589310243389-96a5483213a8'),rating:'4.6',reviews:9},
 {id:27,name:'Leather Slip-On',cat:'Shoes',price:3890,collection:'RED POLO',colors:['#25231f'],img:image('photo-1614252235316-8c857d38b5f4'),rating:'4.7',reviews:9},
 {id:28,name:'Fine Gauge Crew Socks',cat:'Socks',price:690,collection:'UDUOOCI',colors:['#d9d1c3','#353a35'],img:image('photo-1582966772680-860e372bb558'),rating:'4.8',reviews:14},
 {id:29,name:'Classic Pique Polo',cat:'T-Shirts',price:2190,collection:'RED POLO',colors:['#a32c2a','#edeae2'],img:image('photo-1625910513413-5fc45a5e2e3c'),rating:'4.9',reviews:26,tag:'Bestseller'},
 {id:30,name:'Poplin Vacation Shirt',cat:'Shirts',price:2590,collection:'UDUOOCI',colors:['#e4dfd6','#232824'],img:image('photo-1596755094514-f87e34085b2c'),rating:'4.7',reviews:7,tag:'New'}
];
const categories=[['T-SHIRTS','Everyday essentials.',image('photo-1521572163474-6864f9cf17ab',600)],['SHIRTS','Classic, refined, effortless.',image('photo-1602810318383-e386cc2a3ccf',600)],['BELTS','Details that complete the look.',image('photo-1624222247344-550fb60583dc',600)],['SHOES','Built for everyday movement.',image('photo-1542291026-7eec264c27ff',600)],['SOCKS','Simple essentials, refined.',image('photo-1586350977771-b3b0abd50c82',600)]];
let cart=JSON.parse(localStorage.getItem('rp-cart')||'[]'); let wishlist=JSON.parse(localStorage.getItem('rp-wishlist')||'[]'); let activeCategory='All';
const money=n=>`₹${n.toLocaleString('en-IN')}`; const $=s=>document.querySelector(s);
function productCard(p){return `<article class="product-card"><div class="product-image"><img loading="lazy" src="${p.img}" alt="${p.name}"/><button class="wish ${wishlist.includes(p.id)?'active':''}" data-wish="${p.id}" aria-label="Add ${p.name} to wishlist">${wishlist.includes(p.id)?'♥':'♡'}</button>${p.tag?`<span class="badge">${p.tag}</span>`:''}</div><div class="product-meta"><h3>${p.name}</h3><p>${p.cat} · ${p.collection}</p><p class="price">${money(p.price)}</p><div class="color-dots">${p.colors.map(c=>`<i class="dot" style="background:${c}"></i>`).join('')}</div><button class="quick-add" data-add="${p.id}">Quick add +</button></div></article>`}
function render(){ $('#category-grid').innerHTML=categories.map(c=>`<a class="category-card" href="#shop" data-category="${c[0].replace('T-SHIRTS','T-Shirts').replace('SHOES','Shoes').replace('SOCKS','Socks').replace('SHIRTS','Shirts').replace('BELTS','Belts')}"><img loading="lazy" src="${c[2]}" alt="${c[0]}"/><div class="category-copy"><h3>${c[0]}</h3><p>${c[1]}</p></div></a>`).join(''); const featured=products.filter(p=>p.featured); $('#featured-products').innerHTML=featured.map(productCard).join(''); $('#new-products').innerHTML=products.filter(p=>p.tag==='New').slice(0,5).map(productCard).join(''); updateCounts();}
function updateCounts(){const total=cart.reduce((a,i)=>a+i.qty,0);$('#cart-count').textContent=total;$('#drawer-count').textContent=total;$('#wishlist-count').textContent=wishlist.length;$('#cart-items').innerHTML=cart.length?cart.map(i=>`<div class="cart-row"><img src="${i.img}" alt="${i.name}"/><div><h4>${i.name}</h4><p>${i.cat} · One size</p><p>${money(i.price)} × ${i.qty}</p><button class="cart-remove" data-remove="${i.id}">Remove</button></div><strong>${money(i.price*i.qty)}</strong></div>`).join(''):'<div class="empty-state">Your bag is currently empty.<br/><br/><a class="underlined" href="#shop" data-action="close">Discover the collection ↗</a></div>';const sum=cart.reduce((a,i)=>a+i.price*i.qty,0);$('#cart-total').textContent=money(sum);$('#shipping-away').textContent=sum>=2500?'complimentary shipping':money(2500-sum);localStorage.setItem('rp-cart',JSON.stringify(cart));localStorage.setItem('rp-wishlist',JSON.stringify(wishlist));}
function openPanel(id){$('#overlay').classList.add('open');$(id).classList.add('open')} function closePanels(){$('#overlay').classList.remove('open');document.querySelectorAll('.drawer,.modal,.search-panel').forEach(x=>x.classList.remove('open'))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2200)}
function showCategory(cat){activeCategory=cat;const list=cat==='All'?products:products.filter(p=>p.cat===cat);$('#featured-products').innerHTML=list.slice(0,12).map(productCard).join('');$('#shop').scrollIntoView({behavior:'smooth'});}
function modal(p){$('#modal-content').innerHTML=`<div class="modal-product"><img src="${p.img}" alt="${p.name}"/><div class="modal-details"><p class="eyebrow">${p.cat} / ${p.collection}</p><h2>${p.name}</h2><p>★★★★★ &nbsp; ${p.rating} (${p.reviews} reviews)</p><p class="price">${money(p.price)}</p><p>A considered everyday piece, cut for a clean silhouette and made to move through the day with you.</p><div class="detail-line">Color <span>${p.colors.map(c=>`<i class="dot" style="display:inline-block;background:${c}"></i>`).join(' ')}</span></div><div class="detail-line">Select size <span>S &nbsp; M &nbsp; L &nbsp; XL</span></div><button class="button button-dark full-width" data-add="${p.id}">Add to bag <span>↗</span></button><div class="detail-line">Description <span>+</span></div><div class="detail-line">Material & care <span>+</span></div><div class="detail-line">Shipping & returns <span>+</span></div></div></div>`;openPanel('#product-modal')}
function add(id){const p=products.find(x=>x.id===id), found=cart.find(x=>x.id===id);if(found)found.qty++;else cart.push({...p,qty:1});updateCounts();toast(`${p.name} added to your bag`)}
document.addEventListener('click',e=>{const action=e.target.closest('[data-action]')?.dataset.action;if(action==='cart'){openPanel('#cart-drawer');return}if(action==='wishlist'){toast(`${wishlist.length} saved piece${wishlist.length===1?'':'s'}`);return}if(action==='menu'){openPanel('#mobile-drawer');return}if(action==='search'){openPanel('#search-panel');setTimeout(()=>$('#search-input').focus(),100);return}if(action==='close'){closePanels();return}if(action==='checkout'){toast('Checkout is ready for your details');return}const addId=e.target.closest('[data-add]')?.dataset.add;if(addId){add(Number(addId));return}const wishId=e.target.closest('[data-wish]')?.dataset.wish;if(wishId){const id=Number(wishId);wishlist=wishlist.includes(id)?wishlist.filter(x=>x!==id):[...wishlist,id];updateCounts();render();toast(wishlist.includes(id)?'Saved to your wishlist':'Removed from your wishlist');return}const removeId=e.target.closest('[data-remove]')?.dataset.remove;if(removeId){cart=cart.filter(x=>x.id!==Number(removeId));updateCounts();return}const category=e.target.closest('[data-category]')?.dataset.category;if(category){e.preventDefault();closePanels();showCategory(category);return}const card=e.target.closest('.product-card');if(card&&!e.target.closest('button')){const name=card.querySelector('h3').textContent;modal(products.find(p=>p.name===name));}});
$('#overlay').addEventListener('click',closePanels);document.querySelectorAll('[data-scroll]').forEach(b=>b.addEventListener('click',()=>$('#featured-products').scrollBy({left:b.dataset.scroll==='next'?360:-360,behavior:'smooth'})));$('#search-input').addEventListener('input',e=>{const q=e.target.value.toLowerCase();$('#search-results').innerHTML=q?products.filter(p=>`${p.name} ${p.cat} ${p.collection}`.toLowerCase().includes(q)).slice(0,7).map(p=>`<a class="search-result" href="#shop" data-add="${p.id}"><img src="${p.img}" alt=""/><div><p>${p.name}</p><span>${p.cat} · ${money(p.price)}</span></div></a>`).join(''):'<p class="muted">Search by product, category or collection.</p>'});$('#newsletter-form').addEventListener('submit',e=>{e.preventDefault();$('#newsletter-status').textContent='Thank you. You’re on the list.';e.target.reset()});
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js')); render();
